// <auto-generated />
namespace Lab1_WOMU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtotpris : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtotpris));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051301470_addtotpris"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
